version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "zero-etl-demo"
s3_prefix = "zero-etl-demo"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
